### ISSUE TITLE
sending standalone server to host:port with nothing listening results in death by type error

### ISSUE THREAD

**Issue by cburroughs** [mnot/redbot#122]
```
Starting standalone server on PID 13283...
* Static files loaded.
Traceback (most recent call last):
  File "bin/webui.py", line 602, in <module>
    standalone_main("", port, static_dir)
  File "bin/webui.py", line 556, in standalone_main
    thor.run()
  File "/home/web/sites/redbot/venv/lib/python2.6/site-packages/thor/loop.py", line 113, in run
    self._run_fd_events()
  File "/home/web/sites/redbot/venv/lib/python2.6/site-packages/thor/loop.py", line 301, in _run_fd_events
    self._fd_event(event, fileno)
  File "/home/web/sites/redbot/venv/lib/python2.6/site-packages/thor/loop.py", line 164, in _fd_event
    self._fd_targets[fd].emit(event)
  File "/home/web/sites/redbot/venv/lib/python2.6/site-packages/thor/events.py", line 109, in emit
    e(*args)
  File "/home/web/sites/redbot/venv/lib/python2.6/site-packages/thor/tcp.py", line 373, in handle_conn_error
    self.emit('connect_error', err_type, err)
  File "/home/web/sites/redbot/venv/lib/python2.6/site-packages/thor/events.py", line 109, in emit
    e(*args)
  File "/home/web/sites/redbot/venv/lib/python2.6/site-packages/thor/http/client.py", line 275, in _handle_connect_error
    self.input_error(ConnectError(err))
  File "/home/web/sites/redbot/venv/lib/python2.6/site-packages/thor/http/client.py", line 390, in input_error
    self.emit('error', err)
  File "/home/web/sites/redbot/venv/lib/python2.6/site-packages/thor/events.py", line 109, in emit
    e(*args)
  File "/home/web/sites/redbot/venv/lib/python2.6/site-packages/redbot/fetch.py", line 292, in _response_error
    self.finish_task()
  File "/home/web/sites/redbot/venv/lib/python2.6/site-packages/redbot/fetch.py", line 117, in finish_task
    self.done_cb()
  File "bin/webui.py", line 270, in done
    formatter.finish_output()
  File "/home/web/sites/redbot/venv/lib/python2.6/site-packages/redbot/formatter/html.py", line 321, in finish_output
    'replace'
TypeError: coercing to Unicode: need string or buffer, int found
```

**Comment by mnot** [comment]
Should be fixed, please reopen if you still see.
