### ISSUE TITLE
'NoneType' object has no attribute 'write' on timeout

### ISSUE THREAD

**Issue by cburroughs** [mnot/redbot#149]
Started server, it ran happily for a few days, and then died with this message apparanlty related to mis-handling a timeout:

```
Starting standalone server on PID 26815...
http://localhost:7778/
2484K in 0K out for <http://www.addthis.com/blog/> (descend True)Traceback (most recent call last):
  File "bin/webui.py", line 673, in <module>
    standalone_main("", port, static_dir)
  File "bin/webui.py", line 626, in standalone_main
    thor.run()
  File "/home/web/sites/redbot/env/lib/python2.6/site-packages/thor/loop.py", line 148, in run
    what()
  File "/home/web/sites/redbot/env/lib/python2.6/site-packages/thor/loop.py", line 211, in cb
    callback(*args)
  File "bin/webui.py", line 373, in timeoutError
    self.output(error_template % ("RED timeout."))
  File "bin/webui.py", line 369, in output
    self.response_body(chunk.encode(charset, 'replace'))
  File "/home/web/sites/redbot/env/lib/python2.6/site-packages/thor/http/server.py", line 249, in response_body
    self.http_conn.output_body(chunk)
  File "/home/web/sites/redbot/env/lib/python2.6/site-packages/thor/http/common.py", line 438, in output_body
    self.output(chunk)
  File "/home/web/sites/redbot/env/lib/python2.6/site-packages/thor/http/server.py", line 115, in output
    self.tcp_conn.write(data)
AttributeError: 'NoneType' object has no attribute 'write'
```

**Comment by spaceone** [comment]
I got the same error.

**Comment by mnot** [comment]
The server-side of Thor isn't really production-ready at the moment, more for testing. That said, if you see this (or other bugs), I'd love to hear about them (ideally on mnot/thor).

**Comment by mnot** [comment]
I've been doing a bit of background work on standalone mode, and it should be more solid now (it's currently running on redbot.org, albeit behind an apache proxy).

Please see if it's any better for you; if you find additional issues, please file a bug.

Thanks!
