### ISSUE TITLE
CPU burn

### ISSUE THREAD

**Issue by mnot** [mnot/redbot#241]
Getting 100% CPU intermittently. Sometimes still serving, sometimes wedged (see #240).

Latest incident:

<img width="268" alt="Screen Shot 2019-11-01 at 9 39 46 am" src="https://user-images.githubusercontent.com/74384/67990943-96abb580-fc8b-11e9-949e-ce4f87a6b06a.png">

Corresponding logs:

~~~
Oct 31 17:24:43 cloud.mnot.net redbot[3152169]: Exception in thread Thread-13:
Oct 31 17:24:43 cloud.mnot.net redbot[3152169]: Traceback (most recent call last):
Oct 31 17:24:43 cloud.mnot.net redbot[3152169]:   File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
Oct 31 17:24:43 cloud.mnot.net redbot[3152169]:     self.run()
Oct 31 17:24:43 cloud.mnot.net redbot[3152169]:   File "/usr/lib/python3.7/threading.py", line 870, in run
Oct 31 17:24:43 cloud.mnot.net redbot[3152169]:     self._target(*self._args, **self._kwargs)
Oct 31 17:24:43 cloud.mnot.net redbot[3152169]:   File "/usr/lib/python3.7/multiprocessing/pool.py", line 486, in _handle_results
Oct 31 17:24:43 cloud.mnot.net redbot[3152169]:     cache[job]._set(i, obj)
Oct 31 17:24:43 cloud.mnot.net redbot[3152169]:   File "/usr/lib/python3.7/multiprocessing/pool.py", line 662, in _set
Oct 31 17:24:43 cloud.mnot.net redbot[3152169]:     self._callback(self._value)
Oct 31 17:24:43 cloud.mnot.net redbot[3152169]:   File "/usr/lib/python3.7/site-packages/thor/tls.py", line 85, in _continue_connect
Oct 31 17:24:43 cloud.mnot.net redbot[3152169]:     self.sock, do_handshake_on_connect=False, server_hostname=self.host
Oct 31 17:24:43 cloud.mnot.net redbot[3152169]:   File "/usr/lib/python3.7/ssl.py", line 423, in wrap_socket
Oct 31 17:24:43 cloud.mnot.net redbot[3152169]:     session=session
Oct 31 17:24:43 cloud.mnot.net redbot[3152169]:   File "/usr/lib/python3.7/ssl.py", line 817, in _create
Oct 31 17:24:43 cloud.mnot.net redbot[3152169]:     if sock.getsockopt(SOL_SOCKET, SO_TYPE) != SOCK_STREAM:
Oct 31 17:24:43 cloud.mnot.net redbot[3152169]: OSError: [Errno 9] Bad file descriptor
~~~

Not sure there's really a correlation there, though; other incident within view doesn't have any corresponding log of note. There are lots of timeouts, though, from spam requests, and some corresponding file descriptor growth:

<img width="603" alt="Screen Shot 2019-11-01 at 9 44 59 am" src="https://user-images.githubusercontent.com/74384/67991139-53057b80-fc8c-11e9-823f-379c9dfc83c7.png">

... which to me does suggest we're leaking.

**Comment by mnot** [comment]
Oh, and interestingly, this didn't happen nearly as much on Rackspace (but it did happen), and it seemed less invasive when it did (which is why I mostly ignored it then). Not sure what's different on Linode.

**Comment by mnot** [comment]
Seems to be happening a lot less; could be a transient hosting, OS or py issue, or perhaps even #218
