### ISSUE TITLE
Missing jinja2 module in Dockerfile

### ISSUE THREAD

**Issue by Phyliares** [mnot/redbot#263]
Hello, jinja2 module installation is missing in `Dockerfile`

```
~/tools/redbot$ diff Dockerfile Dockerfile_orig
5c5
< RUN pip install --trusted-host pypi.python.org thor markdown netaddr jinja2
---
> RUN pip install --trusted-host pypi.python.org thor markdown netaddr
```
Otherwise docker container doesn't build well

```
~/tools/redbot$ docker run -p 8000:80 redbot
Traceback (most recent call last):
  File "bin/redbot_daemon.py", line 22, in <module>
    from redbot.webui import RedWebUi
  File "/redbot/redbot/webui.py", line 34, in <module>
    from redbot.message import HttpRequest
  File "/redbot/redbot/message/__init__.py", line 19, in <module>
    from redbot.message.headers import HeaderProcessor
  File "/redbot/redbot/message/headers/__init__.py", line 35, in <module>
    from ._utils import RE_FLAGS, parse_date, unquote_string, split_string, parse_params
  File "/redbot/redbot/message/headers/_utils.py", line 9, in <module>
    from ._notes import (
  File "/redbot/redbot/message/headers/_notes.py", line 7, in <module>
    from redbot.speak import Note, categories, levels
  File "/redbot/redbot/speak.py", line 15, in <module>
    from jinja2 import Markup, escape
ModuleNotFoundError: No module named 'jinja2'
```

**Comment by mnot** [comment]
See how that works for you. Thanks for the report.
